# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

# Default values for all Aether Helm charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  fullnameOverride: "chronos"
  nameOverride: ""

import:
  grafana:
    enabled: false
  prometheus:
    chronos:
      enabled: true
  chronos-exporter:
    enabled: true
  aether-enterprise-portal:
    enabled: true
  rasa:
    enabled: true

aether-enterprise-portal:
  grafana:
    proxyEnabled: false
    service: chronos-grafana
  prometheus:
    proxyEnabled: true
    service: chronos-prometheus
  rasa:
    proxyEnabled: true
    service: chronos-umbrella-rasa
  mailhog:
    proxyEnabled: true
    service: chronos-mailhog

grafana:
  image:
    tag: 8.1.8
  fullnameOverride: chronos-grafana
  adminPassword: admin@123
  sidecar:
    dashboards:
       enabled: true
       label: chronos_dashboard
       labelValue: chronos-dashboard
    datasources:
       enabled: true
       label: chronos_datasource
       labelValue: chronos-datasource
  source:
  - name: chronos
    protocol: http
    service: chronos-prometheus
    port: 80
  grafana.ini:
    log:
      level: debug
    server:
      domain: aether-roc-gui:8183
      root_url: "%(protocol)s://%(domain)s/grafana/"
      serve_from_sub_path: true
    security:
      allow_embedding: true
    auth:
     disable_login_form: false
     oauth_auto_login: false
    auth.anonymous:
      enabled: false
      hide_version: false
# Disabled other auth types for the moment - see aether-roc-gui/docs/grafana.md
    auth.proxy:
      enabled: false
      header_name: X-WEBAUTH-USER
      header_property: username
      auto_sign_up: true
      enable_login_token: true
    auth.jwt:
      enabled: false
      header_name: X-JWT-Assertion
      username_claim: name
      email_claim: email
      jwk_set_url: "https://keycloak.opennetworking.org/auth/realms/master/protocol/openid-connect/certs"
      cache_ttl: 60m  
    auth.generic_oauth:
      enabled: false
      client_id: aether-roc-gui
#      client_secret: YWV0aGVyLXJvYy1ndWkK
      scopes: "openid profile email groups"
      empty_scopes: false
      auth_url: "http://k3u-keycloak:5557/auth/realms/master/protocol/openid-connect/auth"
      token_url: "http://k3u-keycloak:5557/auth/realms/master/protocol/openid-connect/token"
      api_url: "http://k3u-keycloak:5557/auth/realms/master/protocol/openid-connect/userinfo"
      allowed_domains: opennetworking.org
      allow_sign_up: true
      name: KeyCloak

prometheus-chronos:
  alertmanager:
    enabled: false
    persistentVolume:
      enabled: false
  server:
    persistentVolume:
      enabled: false
    fullnameOverride: chronos-prometheus
  pushgateway:
    enabled: false
  nodeExporter:
    enabled: false
  kubeStateMetrics:
    enabled: false
  serverFiles:
    prometheus.yml:
      scrape_configs:
        - job_name: chronos-exporter
          scrape_interval: 2s
          static_configs:
            - targets:
                - chronos-exporter:2112

rasa:
  image:
    repository: onosproject/rasa-sanic
    tag: v0.1.4
#  fullnameOverride: "chronos-rasa"
  applicationSettings:
    token: chronos-rasa-token
    endpoints:
      models:
        enabled: true
        url: http://rasa-model-server:8080/models/20220101-000000-aether-trained
        token: chronos-rasa-model-server-token
        wait_time_between_pulls: 60
      trackerStore:
        enabled: false
    credentials:
      enabled: true
      additionalChannelCredentials:
        rest:
        socketio:
          user_message_evt: user_uttered
          bot_message_evt: bot_uttered
          session_persistence: true/false
    telemetry:
      enabled: false
  postgresql:
    install: false

rasa-action-server:
  smtp:
    server: chronos-mailhog

mailhog:
  fullnameOverride: chronos-mailhog