# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: podmemorystores.podmemory.atomix.io
spec:
  group: podmemory.atomix.io
  scope: Namespaced
  names:
    kind: PodMemoryStore
    listKind: PodMemoryStoreList
    plural: podmemorystores
    singular: podmemorystore
    shortNames:
      - pms
  versions:
    - name: v1beta1
      served: true
      storage: true
      subresources:
        status: {}
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              description: |-
                The specification for the store.
              type: object
              properties: {}
            status:
              type: object
              properties:
                state:
                  type: string
                  default: NotReady
                  enum:
                    - NotReady
                    - Ready
      additionalPrinterColumns:
        - name: Status
          type: string
          description: The store state
          jsonPath: .status.state