# SPDX-FileCopyrightText: 2022-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

nameOverride: ""
fullnameOverride: "rasa-model-server"

replicaCount: 1
annotations: {}

image:
  repository: onosproject/rasa-model-server
  tag: v0.1.7
  pullPolicy: IfNotPresent
  pullSecrets: []

service:
  type: ClusterIP

modelfiles: /opt/rasa-models/
