apiVersion: v2
appVersion: v2.1.0
description: Poll Prometheus for core changes and push to Kafka
home: https://www.opennetworking.org/aether/
keywords:
- aether
kubeVersion: '>=1.17.0'
maintainers:
- email: support@opennetworking.org
  name: Aether Ops team
name: sdcore-prom-kafka
type: application
version: 1.0.0
