# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

# Default values for aether-enterprise-portal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: onosproject/aether-enterprise-portal
  tag: v0.1.1
  pullPolicy: IfNotPresent
  pullSecrets: []

imagePullSecrets: []
nameOverride: ""
fullnameOverride: "aether-enterprise-portal"

## Client service.
service:
  enabled: true
  ## Service name is user-configurable for maximum service discovery flexibility.
  name: aether-enterprise-portal
  type: LoadBalancer
  external:
    nodePort: 31195

ingress:
  enabled: false

ports:
  web:
    containerPort: 80
    protocol: TCP

# Enable by giving a value like https://keycloak-dev.onlab.us/auth/realms/master
# make sure this is reachable at https://keycloak-dev.onlab.us/auth/realms/master/.well-known/openid-configuration
openidc:
  issuer:

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

aetherservices:
  chronos-exporter:
    http: 2112
    protocol: http
    streamTimeout: 3600

rasa:
  proxyEnabled: false
  service: rasa
  protocol: http
  port: 5005

mailhog:
  proxyEnabled: false
  service: mailhog
  protocol: http
  port: 8025

grafana:
  proxyEnabled: false
  service: grafana
  protocol: http
  port: 80

prometheus:
  proxyEnabled: false
  service: prometheus
  protocol: http
  port: 80
  credentials:
    username: toBeOverridden
    password: toBeOverridden

Nginx:
  port: 80
