{{/*
# Copyright 2020-present Open Networking Foundation

# SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.config.gnbsim.deploy }}
---
apiVersion: v1
kind: Service
metadata:
  name: gnbsim
  labels:
{{ tuple "gnbsim" . | include "5g-ransim-plane.metadata_labels" | indent 4 }}
{{- with .Values.config.gnbsim.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
{{- end }}
spec:
  type: {{ .Values.config.gnbsim.serviceType }}
  selector:
{{ tuple "gnbsim" . | include "5g-ransim-plane.metadata_labels" | indent 4 }}
  ports:
  - name: ngapp
    port: {{ .Values.config.gnbsim.ngapp.port }}
    protocol: SCTP
  - name: http-api
    port: {{ .Values.config.gnbsim.httpServer.port }}
    protocol: TCP
{{- if .Values.config.gnbsim.httpServer.nodePort.enabled }}
    nodePort: {{ .Values.config.gnbsim.httpServer.nodePort.port }}
{{- end }}
{{- if .Values.config.gnbsim.goProfile.enable }}
  - name: profile-http
    port: {{ .Values.config.gnbsim.goProfile.port }}
    protocol: TCP
{{- end }}
{{- end }}
