# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0
---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "prom-label-proxy.fullname" . }}
  labels:
    app: {{ template "prom-label-proxy.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    {{- include "prom-label-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    name: {{ template "prom-label-proxy.fullname" . }}
  ports:
    - name: http
      port: {{ .Values.service.http.port }}
    - name: gnmi
      port: {{ .Values.service.gnmi.port }}

