# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

nameOverride: ""
fullnameOverride: "demo-exporter"

replicaCount: 1
annotations: {}

image:
  repository: onosproject/sdcore-adapter
  tag: v0.2.12
  pullPolicy: IfNotPresent
  pullSecrets: []

service:
  type: ClusterIP
