# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Test Etcd Driver

on:
  push:
    branches:
      - 'master'
    tags:
      - 'drivers/etcd/v*'
    paths:
      - 'drivers/etcd/**'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Go linter
        uses: ./.github/actions/go/lint
        with:
          component: drivers/etcd

  test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Test atomix.io/etcd@v3
        uses: ./.github/actions/go/test
        with:
          component: drivers/etcd
          package: github.com/atomix/atomix/drivers/etcd/v3/driver/...
