{{/*
# Copyright 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0
*/}}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "network-test.fullname" . }}
  labels:
    {{- include "network-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "network-test.selectorLabels" . | nindent 4 }}
