# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Release Atomix

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Publish Helm chart
        uses: ./.github/actions/helm/publish
        with:
          component: atomix
