# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Test Atomix

on:
  push:
    branches:
      - 'master'
    paths:
      - 'chart/**'
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Test Helm chart
        uses: ./.github/actions/helm/test
        with:
          component: atomix
