{{/*
# Copyright 2020-present Open Networking Foundation
# SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.podsecuritypolicy.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: role:psp:upf
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:upf
subjects:
- kind: Group
  name: system:serviceaccounts:{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
{{- end }}
