# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-datasources-templated
  namespace: {{ .Release.Namespace }}
  labels:
          grafana_datasource: "aether-roc-gui"
data:
  prom-datasources.yaml: |
     apiVersion: 1
     datasources:
     {{- range .Values.grafana.source }}
     - name: datasource-{{ .name }}
       url: {{ .protocol }}://{{ tpl .service $ }}:{{ .port }}
       type: prometheus
       access: proxy
       jsonData:
         oauthPassThru: true
     {{- end }}

