# SPDX-FileCopyrightText: 2022-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

nameOverride: ""
fullnameOverride: "rasa-action-server"

replicaCount: 1
annotations: {}

image:
  repository: onosproject/rasa-action-server
  tag: v0.1.7
  pullPolicy: IfNotPresent
  pullSecrets: []

service:
  type: ClusterIP

smtp:
  server: mailhog
  port: 1025