# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

## Keycloak authentication parameters
## ref: https://github.com/bitnami/containers/tree/main/bitnami/keycloak#admin-credentials
##
auth:
  ## @param auth.adminUser Keycloak administrator user
  ##
  adminUser: admin
  ## @param auth.adminPassword Keycloak administrator password for the new user
  ##
  adminPassword: admin

## @section keycloak-config-cli parameters

## Configuration for keycloak-config-cli
## ref: https://github.com/adorsys/keycloak-config-cli
##
keycloakConfigCli:
  ## @param keycloakConfigCli.enabled Whether to enable keycloak-config-cli job
  ##
  enabled: true
  ## @param keycloakConfigCli.command Command for running the container (set to default if not set). Use array form
  ##
  command:
    - java
    - -jar
    - /opt/bitnami/keycloak-config-cli/keycloak-config-cli.jar
  ## @param keycloakConfigCli.configuration keycloak-config-cli realms configuration
  ## NOTE: nil keys will be considered files to import locally
  ## Example:
  ## configuration:
  ##   realm1.json: |
  ##     {
  ##       "realm": "realm1",
  ##       "clients": []
  ##     }
  ##   files/realm2.yaml:
  ##   realm3.yaml: |
  ##     realm: realm3
  ##     clients: []
  ##
  configuration:
    realm-master.json: |
      {
        "realm": "master",
        "displayName": "Aether Keycloak",
        "displayNameHtml": "<img src='https://opennetworking.org/wp-content/uploads/2020/02/aether-logo.png'></img>",
        "accessTokenLifespan": 86400,
        "ssoSessionMaxLifespan": 86400,
        "clients": [
          {
            "clientId": "aether-roc-gui",
            "name": "Aether ROC GUI",
            "rootUrl": "http://aether-roc-gui:31194",
            "adminUrl": "http://aether-roc-gui:31194",
            "enabled": true,
            "clientAuthenticatorType": "client-secret",
            "redirectUris": [
              "http://aether-roc-gui:8183/*",
              "http://localhost:8183/*",
              "http://localhost:4200/*",
              "http://aether-roc-gui:31194/*"
            ],
            "webOrigins": [
              "http://localhost:8183",
              "http://localhost:4200",
              "http://aether-roc-gui:8183",
              "http://aether-roc-gui:31194"
            ],
            "protocol": "openid-connect",
            "fullScopeAllowed": true,
            "defaultClientScopes": [
              "profile",
              "email"
            ],
            "optionalClientScopes": [
              "roles",
              "groups",
              "offline_access"
            ]
          }
        ],
        "clientScopes": [
          {
            "name": "groups",
            "description": "Groups scope",
            "protocol": "openid-connect",
            "attributes": {
              "include.in.token.scope": "true",
              "display.on.consent.screen": "true"
            },
            "protocolMappers": [
              {
                "name": "Groups Mapper",
                "protocol": "openid-connect",
                "protocolMapper": "oidc-group-membership-mapper",
                "consentRequired": false,
                "config": {
                  "full.path": "false",
                  "id.token.claim": "true",
                  "access.token.claim": "true",
                  "claim.name": "groups",
                  "userinfo.token.claim": "true"
                }
              }
            ]
          }
        ],
        "groups": [
          {
            "name": "AetherROCAdmin",
            "path": "/AetherROCAdmin"
          },
          {
            "name": "EnterpriseAdmin",
            "path": "/EnterpriseAdmin"
          },
          {
            "name": "acme",
            "path": "/acme"
          },
          {
            "name": "aiab-enterprise",
            "path": "/aiab-enterprise"
          },
          {
            "name": "defaultent",
            "path": "/defaultent"
          },
          {
            "name": "starbucks",
            "path": "/starbucks"
          },
          {
            "name": "charactersGroup",
            "path": "/charactersGroup"
          },
          {
            "name": "mixedGroup",
            "path": "/mixedGroup"
          }
        ],
      "users": [
          {
            "username" : "alicea",
            "enabled" : true,
            "totp" : false,
            "emailVerified" : false,
            "firstName" : "Alice",
            "lastName" : "Admin",
            "email" : "alicea@opennetworking.org",
            "credentials": [
              {
                "type": "password",
                "value": "password"
              }
            ],
            "realmRoles" : [ "default-roles-master" ],
            "groups" : [ "/mixedGroup", "/AetherROCAdmin" ],
            "clientRoles": {
              "account": [
                "view-profile",
                "manage-account"
              ]
            },
          },
          {
            "username" : "bobc",
            "enabled" : true,
            "totp" : false,
            "emailVerified" : false,
            "firstName" : "Bob",
            "lastName" : "Cratchit",
            "email" : "bobc@opennetworking.org",
            "credentials": [
              {
                "type": "password",
                "value": "password"
              }
            ],
            "realmRoles" : [ "default-roles-master" ],
            "groups" : [ "/mixedGroup", "/charactersGroup" ],
            "clientRoles": {
              "account": [
                "view-profile",
                "manage-account"
              ]
            },
          },
          {
            "username" : "charlieb",
            "enabled" : true,
            "totp" : false,
            "emailVerified" : false,
            "firstName" : "Charlie",
            "lastName" : "Brown",
            "email" : "charlieb@opennetworking.org",
            "credentials": [
              {
                "type": "password",
                "value": "password"
              }
            ],
            "realmRoles" : [ "default-roles-master" ],
            "groups" : [ "/charactersGroup" ],
            "clientRoles": {
              "account": [
                "view-profile",
                "manage-account"
              ]
            },
          },
          {
            "username" : "daisyd",
            "enabled" : true,
            "totp" : false,
            "emailVerified" : false,
            "firstName" : "Daisy",
            "lastName" : "Duke",
            "email" : "daisyd@opennetworking.org",
            "credentials": [
              {
                "type": "password",
                "value": "password"
              }
            ],
            "realmRoles" : [ "default-roles-master" ],
            "groups" : [ "/charactersGroup", "/EnterpriseAdmin", "/starbucks", "/aiab-enterprise" ],
            "clientRoles": {
              "account": [
                "view-profile",
                "manage-account"
              ]
            },
          },
          {
            "username" : "elmerf",
            "enabled" : true,
            "totp" : false,
            "emailVerified" : false,
            "firstName" : "Elmer",
            "lastName" : "Fudd",
            "email" : "elmerf@opennetworking.org",
            "credentials": [
              {
                "type": "password",
                "value": "password"
              }
            ],
            "realmRoles" : [ "default-roles-master" ],
            "groups" : [ "/charactersGroup", "/starbucks", "/aiab-enterprise" ],
            "clientRoles": {
              "account": [
                "view-profile",
                "manage-account"
              ]
            },
          },
          {
            "username" : "fredf",
            "enabled" : true,
            "totp" : false,
            "emailVerified" : false,
            "firstName" : "Fred",
            "lastName" : "Flintstone",
            "email" : "fredf@opennetworking.org",
            "credentials": [
              {
                "type": "password",
                "value": "password"
              }
            ],
            "realmRoles" : [ "default-roles-master" ],
            "groups" : [ "/charactersGroup", "/EnterpriseAdmin", "/acme", "defaultent" ],
            "clientRoles": {
              "account": [
                "view-profile",
                "manage-account"
              ]
            },
          },
          {
            "username" : "gandalfg",
            "enabled" : true,
            "totp" : false,
            "emailVerified" : false,
            "firstName" : "Gandalf",
            "lastName" : "The Grey",
            "email" : "gandalfg@opennetworking.org",
            "credentials": [
              {
                "type": "password",
                "value": "password"
              }
            ],
            "realmRoles" : [ "default-roles-master" ],
            "groups" : [ "/charactersGroup", "/acme", "defaultent" ],
            "clientRoles": {
              "account": [
                "view-profile",
                "manage-account"
              ]
            },
          }
        ]
      }

