# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Secret
metadata:
  name: {{ template "aether-enterprise-portal.fullname" . }}-secret
  labels:
     chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
     release: "{{ .Release.Name }}"
     heritage: "{{ .Release.Service }}"
data:
  {{ $root := . }}
  {{ range $path, $bytes := .Files.Glob "files/certs/*.*" }}
  {{ base $path }}: '{{ $root.Files.Get $path | b64enc }}'
  {{ end }}
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "aether-enterprise-portal.fullname" . }}-api
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  credentials: {{ printf "%s:%s" .Values.prometheus.credentials.username .Values.prometheus.credentials.password | b64enc | b64enc | quote }}
type: Opaque