# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "atomix-bench.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ template "atomix-bench.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "atomix-bench.fullname" . }}
        {{- if eq .Values.apiVersion "v3beta4" }}
        sidecar.atomix.io/inject: "true"
        runtime.atomix.io/profile: {{ template "atomix-bench.fullname" . }}
        {{- else if eq .Values.apiVersion "v3beta3" }}
        proxy.atomix.io/inject: "true"
        proxy.atomix.io/profile: {{ template "atomix-bench.fullname" . }}
        {{- end }}
      annotations:
        {{- if .Values.sidecar.image.tag }}
        sidecar.atomix.io/image: {{ printf "%s:%s" .Values.sidecar.image.repository .Values.sidecar.image.tag }}
        {{- end }}
        {{- with .Values.sidecar.image.pullPolicy }}
        sidecar.atomix.io/imagePullPolicy: {{ . }}
        {{- end }}
    spec:
      containers:
        - name: atomix-bench
          {{- if .Values.image.tag }}
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag }}
          {{- else if .Chart.AppVersion }}
          image: {{ printf "%s:%s" .Values.image.repository .Chart.AppVersion }}
          {{- else }}
          image: {{ .Values.image.repository }}
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - {{ .Values.primitive.kind | lower }}
            - --concurrency={{ .Values.concurrency }}
            - --write-percentage={{ .Values.writePercentage }}
            - --sample-interval={{ .Values.sampleInterval }}
          volumeMounts:
            - name: config
              mountPath: /etc/atomix
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ template "atomix-bench.fullname" . }}-config
