# SPDX-FileCopyrightText: 2022-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

{{- if eq .Values.apiVersion "v3beta3" }}
apiVersion: atomix.io/v3beta3
kind: StorageProfile
metadata:
  name: {{ template "atomix-bench.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  bindings:
    - store:
        name: {{ .Values.store.name }}
        namespace: {{ .Values.store.namespace }}
{{- else if eq .Values.apiVersion "v3beta4"}}
apiVersion: atomix.io/v3beta4
kind: StorageProfile
metadata:
  name: {{ template "atomix-bench.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  routes:
    - store:
        name: {{ .Values.store.name }}
        namespace: {{ .Values.store.namespace }}
      {{- if .Values.primitive.kind }}
      rules:
        - kind: {{ .Values.primitive.kind }}
          apiVersion: {{ .Values.primitive.apiVersion }}
          {{- with .Values.primitive.config }}
          config:
{{ toYaml . | indent 12 }}
          {{- end }}
      {{- end }}
{{- end }}