# SPDX-FileCopyrightText: 2022-present Intel Corporation
# SPDX-FileCopyrightText: 2020-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v2
name: aether-roc-umbrella
description: Aether ROC Umbrella chart to deploy all Aether ROC
kubeVersion: ">=1.18.0"
type: application
version: 2.1.36
appVersion: v0.0.0
keywords:
  - aether
  - sdn
home: https://www.opennetworking.org/aether/
maintainers:
  - name: Aether Ops team
    email: support@opennetworking.org
dependencies:
  - name: onos-topo
    condition: import.onos-topo.enabled
    repository: https://charts.onosproject.org
    version: 1.5.0
  - name: onos-config
    condition: import.onos-config.enabled
    repository: https://charts.onosproject.org
    version: 1.8.12
  - name: onos-cli
    condition: import.onos-cli.enabled
    repository: https://charts.onosproject.org
    version: 1.3.15
  - name: aether-roc-api
    condition: import.aether-roc-api.enabled
    repository: "file://../aether-roc-api"
    version: 1.7.14
  - name: aether-roc-gui-v2
    condition: import.aether-roc-gui.v2-0.enabled
    repository: https://charts.aetherproject.org
    version: 2.1.3
  - name: aether-roc-gui
    condition: import.aether-roc-gui.v2-1.enabled
    repository: "file://../aether-roc-gui"
    version: 2.1.20
    alias: aether-roc-gui-v2-1
  - name: sdcore-adapter-v2
    condition: import.sdcore-adapter.v2-0.enabled
    repository: https://charts.aetherproject.org
    version: 2.1.1
    alias: sdcore-adapter-v2-0
  - name: sdcore-prom-kafka
    condition: import.sdcore-prom-kafka.enabled
    repository: "file://../sdcore-prom-kafka"
    version: 1.0.0
    alias: sdcore-prom-kafka
  - name: sdcore-adapter
    condition: import.sdcore-adapter.v2-1.enabled
    repository: "file://../sdcore-adapter"
    version: 2.1.4
    alias: sdcore-adapter-v2-1
  - name: subscriber-proxy
    condition: import.subscriber-proxy.enabled
    repository: "file://../subscriber-proxy"
    version: 0.2.1
  - name: nginx
    alias: sdcore-test-dummy
    condition: import.sdcore-test-dummy.enabled
    repository: https://charts.bitnami.com/bitnami
    version: 13.2.0
  - name: grafana
    condition: import.grafana.enabled
    repository: https://grafana.github.io/helm-charts
    version: 6.49.0
  - name: prometheus
    condition: import.prometheus.amp.enabled
    repository: https://prometheus-community.github.io/helm-charts
    version: 19.3.0
    alias: prometheus-amp
  - name: prometheus
    condition: import.prometheus.acc.enabled
    repository: https://prometheus-community.github.io/helm-charts
    version: 19.3.0
    alias: prometheus-acc
  - name: prometheus
    condition: import.prometheus.ace.enabled
    repository: https://prometheus-community.github.io/helm-charts
    version: 19.3.0
    alias: prometheus-ace
  - name: prom-label-proxy
    condition: import.prom-label-proxy.amp.enabled
    repository: "file://../prom-label-proxy"
    version: 0.1.3
    alias: prom-label-proxy-amp
  - name: prom-label-proxy
    condition: import.prom-label-proxy.acc.enabled
    repository: "file://../prom-label-proxy"
    version: 0.1.3
    alias: prom-label-proxy-acc
  - name: aether-mock-exporter
    condition: import.aether-mock-exporter.enabled
    repository: "file://../aether-mock-exporter"
    version: 0.2.1
