# Copyright 2019-present Open Networking Foundation
#
# SPDX-License-Identifier: Apache-2.0

dependencies:
  - name: cassandra
    version: 0.13.1
    repository: https://charts.helm.sh/incubator
    condition: cassandra.deploy
