# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Test Benchmarking Tool

on:
  push:
    branches:
      - 'master'
    paths:
      - 'bench/**'
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Go linter
        uses: ./.github/actions/go/lint
        with:
          component: bench

  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Go tests
        uses: ./.github/actions/go/test
        with:
          component: bench

  deploy:
    name: Deploy and verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build Docker image
        uses: ./.github/actions/docker/build
        with:
          component: bench
          file: build/Dockerfile

      - name: Test Helm chart
        uses: ./.github/actions/helm/test
        with:
          component: bench
