# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chronos-exporter.fullname" . }}-config
  labels:
    app: {{ template "chronos-exporter.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{ (.Files.Glob "files/configs/*.yaml").AsConfig | indent 2 }}



---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chronos-exporter.fullname" . }}-images
  labels:
    app: {{ template "chronos-exporter.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
binaryData:
  {{ $root := . }}
  {{ range $path, $bytes := .Files.Glob "files/images/*.png" }}
  {{ base $path }}: '{{ $root.Files.Get $path | b64enc }}'
  {{ end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chronos-exporter.fullname" . }}-site-plans
  labels:
    app: {{ template "chronos-exporter.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
binaryData:
  {{ $root := . }}
  {{ range $path, $bytes := .Files.Glob "files/site-plans/fremont/*.svg" }}
  {{ base $path }}: '{{ $root.Files.Get $path | b64enc }}'
  {{ end }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chronos-exporter.fullname" . }}-alert
  labels:
    app: {{ template "chronos-exporter.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{ (.Files.Glob "files/alerts/*.yaml").AsConfig | indent 2 }}
