# SPDX-FileCopyrightText: 2023-present Intel Corporation
#
# SPDX-License-Identifier: Apache-2.0

name: Release Raft Store

on:
  push:
    tags:
      - 'stores/raft/v*'

jobs:
  publish-controller:
    name: Build and push controller
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Publish controller image
        uses: ./.github/actions/docker/publish
        with:
          component: stores/raft
          file: build/controller/Dockerfile
          repository: atomix/raft-controller
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  publish-node:
    name: Build and push node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Publish node image
        uses: ./.github/actions/docker/publish
        with:
          component: stores/raft
          file: build/node/Dockerfile
          repository: atomix/raft-node
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

  publish-helm-chart:
    name: Publish Helm chart
    runs-on: ubuntu-latest
    needs:
      - publish-controller
      - publish-node
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Publish Helm chart
        uses: ./.github/actions/helm/publish
        with:
          component: stores/raft
