{{/*
# SPDX-FileCopyrightText: 2022-present Intel Corporation

# SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.config.upfadapter.deploy }}
---
apiVersion: v1
kind: Service
metadata:
  name: upf-adapter
  labels:
{{ tuple "upfadapter" . | include "5g-control-plane.metadata_labels" | indent 4 }}
spec:
  type: {{ .Values.config.upfadapter.serviceType }}
  selector:
{{ tuple "upfadapter" . | include "5g-control-plane.metadata_labels" | indent 4 }}
  ports:
  - name: pfcp
    port: {{ .Values.config.upfadapter.n4.port }}
    protocol: UDP
{{- if eq .Values.config.upfadapter.serviceType "NodePort" }}
{{- if .Values.config.upfadapter.n4.nodePort }}
    nodePort: {{ .Values.config.upfadapter.n4.nodePort }}
{{- end }}
{{- end }}
  - name: upfadapter-rest
    port: {{ .Values.config.upfadapter.rest.port }}
    protocol: TCP
{{- end }}
