{{/*
# Copyright 2020-present Open Networking Foundation

# SPDX-License-Identifier: Apache-2.0
*/}}

{{- if .Values.config.sctplb.deploy }}
---
apiVersion: v1
kind: Service
metadata:
  name: sctplb
  labels:
{{ tuple "sctplb" . | include "5g-control-plane.metadata_labels" | indent 4 }}
spec:
  type: {{ .Values.config.sctplb.serviceType }}
{{- if .Values.config.sctplb.ngapp.externalIp }}
  externalIPs:
    - {{ .Values.config.sctplb.ngapp.externalIp }}
{{- end }}
  selector:
{{ tuple "sctplb" . | include "5g-control-plane.metadata_labels" | indent 4 }}
  ports:
  - name: ngapp
    port: {{ .Values.config.sctplb.ngapp.port }}
    protocol: SCTP
{{- if eq .Values.config.sctplb.serviceType "NodePort" }}
{{- if .Values.config.sctplb.ngapp.nodePort }}
    nodePort: {{ .Values.config.sctplb.ngapp.nodePort }}
{{- end }}
{{- end }}
{{- end }}
