services:
  gnbsim:
    image: network5gcore/5gc-gnbsim:rel-1.6.5
    container_name: gnbsim
    command: ["/usr/local/bin/gnbsim", "--cfg", "/app/config.yaml"]
    volumes:
      - ./configs/config-1.yaml:/app/config.yaml
    restart: unless-stopped
    networks:
      gnbsim_net:
        ipv4_address: 172.20.0.10

networks:
  gnbsim_net:
    driver: host
    ipam:
      config:
        - subnet: 172.20.0.0/16
