apiVersion: v1
kind: ConfigMap
metadata:
  name: gnbsim-config
  namespace: default
data:
  config.yaml: |
    # Copia aquí el contenido de config-1.yaml

---
apiVersion: v1
kind: Pod
metadata:
  name: gnbsim
  namespace: default
spec:
  containers:
    - name: gnbsim
      image: network5gcore/5gc-gnbsim:rel-1.6.5
      command: ["/usr/local/bin/gnbsim", "--cfg", "/app/config.yaml"]
      volumeMounts:
        - name: config-volume
          mountPath: /app/config.yaml
          subPath: config.yaml
      # resources:
      #   requests:
      #     cpu: "100m"
      #     memory: "128Mi"
      #   limits:
      #     cpu: "500m"
      #     memory: "512Mi"
  volumes:
    - name: config-volume
      configMap:
        name: gnbsim-config
  restartPolicy: Always