# SPDX-FileCopyrightText: 2021-present Open Networking Foundation <info@opennetworking.org>
#
# SPDX-License-Identifier: Apache-2.0
enterprise:
  enterprise-id: tesla
  display-name: Tesla
  image: /chronos-exporter/images/tesla-logo.png
sites:
  - site-id: fremont
    display-name: Fremont, CA
    image: /chronos-exporter/images/los-angeles-us.png
    small-cells:
      - small-cell-id: fremont-sc-north
        display-name: North Cell
        position:
          position-x: 100
          position-y: 50
          site-plan: floor-0
      - small-cell-id: fremont-sc-south
        display-name: South Cell
        position:
          position-x: 100
          position-y: 150
          site-plan: floor-1
      - small-cell-id: fremont-sc-east
        display-name: East Cell
        position:
          position-x: 200
          position-y: 100
          site-plan: floor-2
      - small-cell-id: fremont-sc-west
        display-name: West Cell
        position:
          position-x: 10
          position-y: 100
          site-plan: floor-0
    slices:
      - slice-id: fremont-slice-cameras
        display-name: Cameras Slice
        device-groups:
          - cameras
        applications:
          - nvr-application
          - occupant-counter
      - slice-id: fremont-slice-phones
        display-name: Phones Slice
        device-groups:
          - phones
        applications:
          - expenses-application
    device-groups:
      - device-group-id: phones
        display-name: Phones group
        devices:
          - 752365A
          - 752908B
      - device-group-id: cameras
        display-name: Cameras group
        devices:
          - 7568111
          - 7568112
          - 7568113
          - 7568114
          - 7568115
          - 7568116
          - 7568117
          - 7568118
          - 7568119
    devices:
      - serial-number: 752365A
        imei: 123-456-7891
        display-name: Phone 1
        location: Somewhere
        type: Pixel 5 Phone
        sim: 123-456-789
        position:
          position-x: 110
          position-y: 50
          site-plan: floor-0
      - serial-number: 752908B
        imei: 123-456-7892
        display-name: Phone 2
        location: Somewhere
        type: iPhone 11
        sim: 123-456-788
        position:
          position-x: 120
          position-y: 60
          site-plan: floor-0
      - serial-number: 7568111
        imei: 123-456-7893
        display-name: Camera 1
        location: Front entrance
        type: Camera
        sim: 123-456-787
        position:
          position-x: 130
          position-y: 70
          site-plan: floor-0
      - serial-number: 7568112
        imei: 123-456-7894
        display-name: Camera 2
        location: South Gate
        type: Camera
        sim: 123-456-786
      - serial-number: 7568113
        imei: 123-456-7895
        display-name: Camera 3
        location: Store Room 1
        type: Camera
        sim: 123-456-785
      - serial-number: 7568114
        imei: 123-456-7896
        display-name: Camera 4
        location: Store Room 2
        type: Camera
        sim: 123-456-784
      - serial-number: 7568115
        imei: 123-456-7897
        display-name: Camera 5
        location: Corridor 1
        type: Camera
        sim: 123-456-783
      - serial-number: 7568116
        imei: 123-456-7898
        display-name: Camera 6
        location: Corridor 2
        type: Camera
        sim: 123-456-782
      - serial-number: 7568117
        imei: 123-456-7899
        display-name: Camera 7
        location: Atrium
        type: Camera
        sim: 123-456-781
      - serial-number: 7568118
        imei:
        display-name: Camera 8
        location: Corridor 3
        type: Camera
      - serial-number: 7568119
        imei:
        display-name: Camera 9
        location: Corridor 4
        type: Camera
    sims:
      - iccid: 123-456-791
        display-name: Sim 11
      - iccid: 123-456-790
        display-name: Sim 10
      - iccid: 123-456-789
        display-name: Sim 9
      - iccid: 123-456-788
        display-name: Sim 8
      - iccid: 123-456-787
        display-name: Sim 7
      - iccid: 123-456-786
        display-name: Sim 6
      - iccid: 123-456-785
        display-name: Sim 5
      - iccid: 123-456-784
        display-name: Sim 4
      - iccid: 123-456-783
        display-name: Sim 3
      - iccid: 123-456-782
        display-name: Sim 2
      - iccid: 123-456-781
        display-name: Sim 1
    site-plans:
      isometric: true
      origin: ORIGIN_TOP_LEFT
      layers:
        - layer-id: Structure
        - layer-id: Text
      site-plan-list:
        - id: floor-0
          svg-file: /chronos-exporter/site-plans/fremont/floor-0.svg
          offsets:
            x-offset: 0
            y-offset: 0
            z-offset: 0
        - id: floor-1
          svg-file: /chronos-exporter/site-plans/fremont/floor-1.svg
          offsets:
            x-offset: 0
            y-offset: 0
            z-offset: 100
        - id: floor-2
          svg-file: /chronos-exporter/site-plans/fremont/floor-2.svg
          offsets:
            x-offset: 0
            y-offset: 0
            z-offset: 200
        - id: floor-3
          svg-file: /chronos-exporter/site-plans/fremont/floor-3.svg
          offsets:
            x-offset: 0
            y-offset: 0
            z-offset: 300
  - site-id: berlin
    display-name: Berlin, DE
    image: /chronos-exporter/images/berlin-deutschland.png
    small-cells:
      - small-cell-id: berlin-sc-north
        display-name: North Cell
      - small-cell-id: berlin-sc-south
        display-name: South Cell
      - small-cell-id: berlin-sc-east
        display-name: East Cell
      - small-cell-id: berlin-sc-west
        display-name: West Cell
    slices:
      - slice-id: berlin-slice-cameras
        display-name: Cameras Slice
        device-groups:
          - cameras
        applications:
          - nvr-application
          - occupant-counter
      - slice-id: berlin-slice-phones
        display-name: Phones Slice
        device-groups:
          - phones
        applications:
          - expenses-application
    device-groups:
      - device-group-id: phones
        display-name: Phones group
        devices:
          - 18876871
          - 18876872
          - 18876873
          - 18876874
          - 18876875
      - device-group-id: cameras
        display-name: Cameras group
        devices:
          - 18876881
          - 18876882
          - 18876883
          - 18876884
          - 18876885
          - 18876886
          - 18876887
          - 18876888
    devices:
      - serial-number: 18876871
        imei: 123-456-7891
        display-name: Phone 1
        location: Somewhere
        type: Pixel 5 Phone
        sim: 123-671-789
      - serial-number: 18876872
        imei: 123-671-7892
        display-name: Phone 2
        location: Somewhere
        type: iPhone 11
        sim: 123-671-788
      - serial-number: 18876873
        imei: 123-671-7893
        display-name: Phone 3
        location: Somewhere
        type: iPhone 11
        sim: 123-671-787
      - serial-number: 18876874
        imei: 123-671-7894
        display-name: Phone 4
        location: Somewhere
        type: iPhone 11
        sim: 123-671-786
      - serial-number: 18876875
        imei: 123-671-7895
        display-name: Phone 5
        location: Somewhere
        type: iPhone 11
        sim: 123-671-785
      - serial-number: 18876881
        imei: 123-671-7896
        display-name: Camera 1
        location: Front entrance
        type: Camera
        sim: 123-671-784
      - serial-number: 18876882
        imei: 123-671-7897
        display-name: Camera 2
        location: South Gate
        type: Camera
        sim: 123-671-783
      - serial-number: 18876883
        imei: 123-671-7898
        display-name: Camera 3
        location: Store Room 1
        type: Camera
        sim: 123-671-782
      - serial-number: 18876884
        imei: 123-671-7899
        display-name: Camera 4
        location: Store Room 2
        type: Camera
        sim: 123-671-781
      - serial-number: 18876885
        imei: 123-671-7900
        display-name: Camera 5
        location: Corridor 1
        type: Camera
        sim: 123-671-780
      - serial-number: 18876886
        imei: 123-671-7901
        display-name: Camera 6
        location: Corridor 2
        type: Camera
        sim: 123-671-779
      - serial-number: 18876887
        imei: 123-671-7902
        display-name: Camera 7
        location: Atrium
        type: Camera
        sim: 123-671-778
      - serial-number: 18876888
        imei:
        display-name: Camera 8
        location: Corridor 2
        type: Camera
    sims:
      - iccid: 123-671-789
        display-name: Sim 9
      - iccid: 123-671-788
        display-name: Sim 8
      - iccid: 123-671-787
        display-name: Sim 7
      - iccid: 123-671-786
        display-name: Sim 6
      - iccid: 123-671-785
        display-name: Sim 5
      - iccid: 123-671-784
        display-name: Sim 4
      - iccid: 123-671-783
        display-name: Sim 3
      - iccid: 123-671-782
        display-name: Sim 2
      - iccid: 123-671-781
        display-name: Sim 1
      - iccid: 123-671-780
        display-name: Sim 1a
      - iccid: 123-671-779
        display-name: Sim 1b
      - iccid: 123-671-778
        display-name: Sim 1c
      - iccid: 123-671-779
        display-name: Sim 1d
      - iccid: 123-671-780
        display-name: Sim 1e
      - iccid: 123-671-781
        display-name: Sim 1f
  - site-id: bengaluru
    display-name: Bengaluru, INDIA
    image: /chronos-exporter/images/bengaluru-india.png
    small-cells:
      - small-cell-id: bengaluru-north
        display-name: North Cell
      - small-cell-id: bengaluru-south
        display-name: South Cell
      - small-cell-id: bengaluru-east
        display-name: East Cell
      - small-cell-id: bengaluru-west
        display-name: West Cell
      - small-cell-id: bengaluru-central
        display-name: Central Cell
      - small-cell-id: bengaluru-east-central
        display-name: East Central Cell
    slices:
      - slice-id: bengaluru-slice-cameras
        display-name: Cameras Slice
        device-groups:
          - cameras
        applications:
          - nvr-application
          - occupant-counter
      - slice-id: begaluru-slice-phones
        display-name: Phones Slice
        device-groups:
          - phones-north
          - phones-south
        applications:
          - expenses-application
      - slice-id: bengaluru-slice-drones
        display-name: Drone Slice
        device-groups:
          - drone-central
          - drone-east
          - drone-west
        applications:
          - drone-application
    device-groups:
      - device-group-id: phones-north
        display-name: Phones North group
        devices:
          - 9870001
          - 9870002
          - 9870003
          - 9870004
          - 9870005
          - 9870006
      - device-group-id: phones-south
        display-name: Phones South group
        devices:
          - 987100A
          - 987101B
          - 987102C
          - 987103D
      - device-group-id: cameras
        display-name: Cameras group
        devices:
          - 9873001
          - 9873002
          - 9873003
          - 9873004
          - 9873005
          - 9873006
          - 9873007
          - 9873008
          - 9873009
      - device-group-id: drone-central
        display-name: Drone Central Group
        devices:
          - 80001XA
          - 80002XB
          - 80003XC
          - 80004XD
          - 80005XE
      - device-group-id: drone-east
        display-name: Drone East Group
        devices:
          - 81001XA
          - 81002XB
          - 81003XC
          - 81004XD
      - device-group-id: drone-west
        display-name: Drone West Group
        devices:
          - 82001XA
          - 82002XB
          - 82003XC
    devices:
      - serial-number: 9870001
        imei: 987-654-3211
        display-name: Phone 1
        location: Electronic city
        type: Pixel 5 Phone
        sim: 987-654-321
      - serial-number: 9870002
        imei: 987-654-3212
        display-name: Phone 2
        location: Marathahalli
        type: Pixel 6 PRO Phone
        sim: 987-654-322
      - serial-number: 9870003
        imei: 987-654-3213
        display-name: Phone 3
        location: RR Nagar
        type: Pixel 6 PRO Phone
        sim: 987-654-323
      - serial-number: 9870004
        imei: 987-654-3214
        display-name: Phone 4
        location: Koramangala
        type: iPhone XR
        sim: 987-654-324
      - serial-number: 9870005
        imei:
        display-name: Phone 5
        location: Marathahalli
        type: iPhone 11 PRO
      - serial-number: 9870006
        imei:
        display-name: Phone 6
        location: Rajajinagar
        type: iPhone 12
      - serial-number: 987100A
        imei: 987-654-3215
        display-name: Phone 7
        location: Banaswadi
        type: iPhone 12 Mini
        sim: 987-654-325
      - serial-number: 987101B
        imei: 987-654-3216
        display-name: Phone 8
        location: Electronic city
        type: Pixel 6 PRO Phone
        sim: 987-654-326
      - serial-number: 987102C
        imei: 987-654-3217
        display-name: Phone 9
        location: Rajajinagar
        type: iPhone 11
        sim: 987-654-327
      - serial-number: 987103D
        imei:
        display-name: Phone 10
        location: some location
        type: Pixel 6 Pro
      - serial-number: 9873001
        imei: 987-654-3218
        display-name: Camera 1
        location: Electronic city
        type: camera
        sim: 987-654-328
      - serial-number: 9873002
        imei: 987-654-3219
        display-name: Camera 2
        location: Rajajinagar
        type: camera
        sim: 987-654-329
      - serial-number: 9873003
        imei: 987-654-3220
        display-name: Camera 3
        location: Banaswadi
        type: camera
        sim: 987-654-330
      - serial-number: 9873004
        imei: 987-654-3221
        display-name: Camera 4
        location:  Koramangala
        type: camera
        sim: 987-654-331
      - serial-number: 9873005
        imei: 987-654-3222
        display-name: Camera 5
        location: Yeswanthpur
        type: camera
        sim: 987-654-332
      - serial-number: 9873006
        imei: 987-654-3223
        display-name: Camera 6
        location: Karihobanahalli
        type: camera
        sim: 987-654-333
      - serial-number: 9873007
        imei:
        display-name: Camera 7
        location: Krishnarajapura
        type: camera
      - serial-number: 9873008
        imei:
        display-name: Camera 8
        location: Kithiganur
        type: camera
      - serial-number: 9873009
        imei:
        display-name: Camera 9
        location: Gundur
        type: camera
      - serial-number: 80001XA
        imei: 987-654-3224
        display-name: Drone 1
        location: Vidyaranyapura
        type: drone
        sim: 987-654-334
      - serial-number: 80002XB
        imei: 987-654-3225
        display-name: Drone 2
        location: Electronic city
        type: drone
        sim: 987-654-335
      - serial-number: 80003XC
        imei: 987-654-3226
        display-name: Drone 3
        location: Electronic city
        type: drone
        sim: 987-654-336
      - serial-number: 80004XD
        imei:
        display-name: Drone 4
        location: RR Nagar
        type: drone
      - serial-number: 80005XE
        imei:
        display-name: Drone 5
        location: Vidyaranyapura
        type: drone
      - serial-number: 81001XA
        imei: 987-654-3227
        display-name: Drone 6
        location: Electronic city
        type: drone
        sim: 987-654-337
      - serial-number: 81002XB
        imei: 987-654-3228
        display-name: Drone 7
        location: Electronic city
        type: drone
        sim: 987-654-338
      - serial-number: 81003XC
        imei:
        display-name: Drone 8
        location: Gundur
        type: drone
      - serial-number: 81004XD
        imei:
        display-name: Drone 9
        location: Kithiganur
        type: drone
      - serial-number: 82001XA
        imei: 987-654-3229
        display-name: Drone 10
        location: Electronic city
        type: drone
        sim: 987-654-339
      - serial-number: 82002XB
        imei:
        display-name: Drone 11
        location: Kithiganur
        type: drone
      - serial-number: 82003XC
        imei:
        display-name: Drone 12
        location: Krishnarajapura
        type: drone
    sims:
      - iccid: 987-654-321
        display-name: Sim 1
      - iccid: 987-654-322
        display-name: Sim 2
      - iccid: 987-654-323
        display-name: Sim 3
      - iccid: 987-654-324
        display-name: Sim 4
      - iccid: 987-654-325
        display-name: Sim 5
      - iccid: 987-654-326
        display-name: Sim 6
      - iccid: 987-654-327
        display-name: Sim 7
      - iccid: 987-654-328
        display-name: Sim 8
      - iccid: 987-654-329
        display-name: Sim 9
      - iccid: 987-654-330
        display-name: Sim 10
      - iccid: 987-654-331
        display-name: Sim 11
      - iccid: 987-654-332
        display-name: Sim 12
      - iccid: 987-654-333
        display-name: Sim 13
      - iccid: 987-654-334
        display-name: Sim 14
      - iccid: 987-654-335
        display-name: Sim 15
      - iccid: 987-654-336
        display-name: Sim 16
      - iccid: 987-654-337
        display-name: Sim 17
      - iccid: 987-654-338
        display-name: Sim 18
      - iccid: 987-654-339
        display-name: Sim 19
      - iccid: 987-654-340
        display-name: Sim 20
      - iccid: 987-654-341
        display-name: Sim 21
applications:
  - application-id: nvr-application
    display-name: Network Video Recorder
  - application-id: occupant-counter
    display-name: Occupant Counting Application
  - application-id: expenses-application
    display-name: Expenses Application
  - application-id: drone-application
    display-name: Drone Application
